### PR TITLE
Show last move #48

### PR DESCRIPTION
**Pull request by agtoever**
Added (yellow) highlight to last played peg, similar to how this is shown on TwixtLive: #48.
Settings in the constants.py file:

- If you want to show this (boolean: True / False) so this is easily turned off. Could be added later to settings menu.
- Color of the border (currently: 'yellow', because this highlights nice with the grey board and the black/red pegs).
- Width of the border (currently: 2, because 1 pixel wasn't visible enough in my opinion).

### CODE REVIEW

**Comment by stevens68** [comment]
I will have a look a.s.a.p 
yellow color makes sense for highlighting; some users might use white for player 1.
Thanks!

**Comment by agtoever** [comment]
Using different colors for each player makes sense. We can add that relatively easily. I'll see if I can do patch that in the current branch... Maybe this afternoon...

**Comment by stevens68** [comment]
> Using different colors for each player makes sense. We can add that relatively easily. I'll see if I can do patch that in the current branch... Maybe this afternoon...

... didn't mean we need different colors for move highlighting; just wanted to say that chosing yellow makes sense (compared white) because some players might prefer white as their peg color. I think yellow highlighting will do.

**Comment by agtoever** [comment]
Ah! Right.

**Comment by stevens68** [comment]
PR#57

**Pull request closed without merging**
